### ISSUE TITLE
Videregående Python-kurs

### ISSUE THREAD

**Issue by okpedersen** [arve0/oppgaver#25]
En oppsummering av https://github.com/kodeklubben-trondheim/tenketank/issues/4

Vi ønsker et kurs som går grundigere gjennom Python, og lærer kidsa mer grundig hvordan Python fungerer. Merk at selv om det er delt opp i del 1/del 2 kan det godt være overlapp mellom disse. Men det er to ulike "fokus".

Mitt forslag til oppbygning av kurset:
**Del 1:**
* Kontrollstrukturer:
  * if-else
  * for/while
* Strings
    * Bruk av innebygde funksjoner (`.replace`, `.join` osv.)
* Lister/Tupler
    * Konkatenering, mutable vs immutable, splicing
    * `.append`, `.pop`, `.sort` m.fl.
    * 2D-lister (for bruk til spillbrett o.l)
* Dictionaries
    * Bruke dictionaries til å lagre data
*  OOP (jeg vet dette er noe omdiskutert, se under)
    * "enkel" OOP
    * ikke public/private, arv,  `__init__()`, eller liknende

**Del 2:**
* Programmering av 2D-spill (Pygame + Pygame zero)

Ang. OOP:
Spillprogrammering uten bruk av enkel OOP blir veldig klønete. En kan selvfølgelig prøve seg med lister, dictionaries osv., men det blir fort tungvint/mye kode med en gang du vil ha 15-20 ulike baller o.l.
Tanken bak bruk av OOP er at det lages enkle klasser som kan instansieres med public variabler, og der du kan lage funksjoner som tilhører objektet. Dette er mye mer hensiktsmessig (etter min mening) når en skal bruke event-loops og likende.

**Comment by arve0** [comment]
**Del1/2**
Dette er i tillegg til eksisterende oppgaver? Slik at det blir Python, Python viderekommende, Python spill?

**2D-lister**
Burde vi vurdere bruke numpy istedenfor 2d-lister?

**Comment by okpedersen** [comment]
**Del1/2**
I utgangspunktet som et kurs, poenget med del1/2 var at det var to ulike fokus. Jeg håpte det var mulig å integrere spill underveis, for å holde motivasjonen oppe. (Ved hjelp av biblioteker som de kan bruke til den enkelte oppgaven).

**2D-lister**
Vi kan helt klart vurdere dette, jeg ser ikke noe i veien for å bruke numpy. Forutsatt at vi bruker conda så bør ikke det være et problem i det hele tatt.
