### ISSUE TITLE
feil med bilder

### ISSUE THREAD

**Issue by arve0** [arve0/oppgaver#4]
Bildene som tidligere ble kopiert (via embeds tag i YAML) fungerer ikke lengre:
http://arve0.github.io/oppgaver/scratch/01-egne/02-labyrint/labyrint.html

Lenkene må oppdateres fra
```
![Velg figur fra biblioteket](hent-fra-bibliotek.png)
```
til:
```
![Velg figur fra biblioteket](../../bilder/hent-fra-bibliotek.png)
```

**Comment by arve0** [comment]
Eller eventuelt finne en måte å gjøre dette på automatisk.

**Comment by gahjelle** [comment]
Enig i at det blir ryddigere med komplette lenker. Jeg kan oppdatere oppgavene.

**Comment by arve0** [comment]
:+1:

**Comment by arve0** [comment]
fixed in #10
