### ISSUE TITLE
Scratch: "stopp alt" har feil farge

### ISSUE THREAD

**Issue by arve0** [arve0/oppgaver#5]
se http://arve0.github.io/oppgaver/scratch/01-egne/02-labyrint/labyrint.html#steg-5-froskekongen-vokter-i-gangene

**Comment by gahjelle** [comment]
Jeg har funnet problemet. Det finnes noen nye tilleggsfunksjoner (under Flere Klosser) i Scratch som er farget svart. En av klossene til Lego WeDo er også oversatt med Stopp _ akkurat som Stopp _-klossen under Styring.

Per nå har vi ingen oppgaver som bruker Lego WeDo (tror jeg), så vi kan lage et umiddelbart hack hvor vi bare gir Lego-funksjonene marginalt andre navn.

Langsiktig tror jeg vi bør høre med sjefsoversetter Torbjørn Skauli om det kanskje finnes en alternativ oversettelse (for eksempel skru på og skru av) som unngår samme navn på to forskjellige klosser. Jeg kontakter Torbjørn.

**Comment by arve0** [comment]
Flyttet til kodeklubben/oppgaver.
